### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by WardPearce** [Prince527GitHub/Swingsonic#1]
Greetings, would it be possible to add a workflow to publish to a docker registry

**Comment by Prince527GitHub** [comment]
Ya it is possible, actually its already available but there is like 0 documentation.
https://github.com/Prince527GitHub/Swingsonic/pkgs/container/swingsonic

**Comment by Prince527GitHub** [comment]
Alright I've updated the readme to include a section on docker using docker compose.
https://github.com/Prince527GitHub/Swingsonic/tree/main#docker
